treble/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from treble_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^treble/', include('treble_app.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

treble_app/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


# Song Model
class Song(models.Model):
    # Unique ID, and has a many-to-many relationship with itself
    song_id = models.IntegerField(primary_key=True)
    track_name = models.CharField(max_length=128)
    artist = models.CharField(max_length=128)
    genre = models.CharField(max_length=128)
    album = models.CharField(max_length=128)
    spotify_uri = models.CharField(max_length=256)
    artwork_url = models.CharField(max_length=256)
    no_of_recommendations = models.IntegerField(null=True)
    recommended_songs = models.ManyToManyField('self', symmetrical=False)

    comments = models.ManyToManyField("Comment", symmetrical=False)

    class Meta:
        unique_together = (("track_name", "artist"),)

    def __str__(self):
        return self.track_name


# User Model
class UserProfile(models.Model):
    user = models.OneToOneField(User)

    username_slug = models.SlugField(unique=True)
    favourites = models.ManyToManyField(Song, symmetrical=False)
    picture = models.ImageField(upload_to='profile_images', blank=True, default="profile_images/default_pic.png")

    comments = models.ManyToManyField("Comment", symmetrical=False)

    def save(self, *args, **kwargs):
        self.username_slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.user.username


# Comment Model
class Comment(models.Model):
    # Unique Comment ID, and has foreign keys Song ID and Username
    # comment_id = models.IntegerField(primary_key=True)
    song_id = models.ForeignKey('Song', default=0)
    username = models.ForeignKey('UserProfile', default=1)
    message = models.CharField(max_length=256)
    datetime = models.DateTimeField(default=timezone.now, blank=False)

    # Reactions are between 0 and 5 where:
    #           0:     Smile Emoji (Default)
    #           1:     Love Emoji
    #           2:     Surprised Emoji
    #           3:     Relieved/Relaxed Emoji
    #           4:     Perfect Emoji
    #           5:     Dissapointed Emoji
    CHOICES = ((0, '☺️'),
               (1, '❤️'),
               (2, '😲'),
               (3, '😌'),
               (4, '👌'),
               (5, '😞'))
    reaction = models.IntegerField(default=0, choices=CHOICES)

    def __str__(self):
        return self.message

templates/treble/about.html
{% extends 'treble/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Us
{% endblock %}

{% block body_block %}
    <h1>About Us</h1>
    <hr>
    <h3>
        We wanted to make Treble because we love music!
    </h3><br/>
    <h4>
        However, often we get narrowed down into the songs we already know we like, and struggle to broaden our
        horizons. <br/>
        So we came up with the idea of an app that can suggest new music to us, based on what we already like! <br/>
        <br/>
        We made Treble for our second year Web Application Development course at the University of Glasgow.
    </h4>
{% endblock %}

templates/treble/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title_block %}

        {% endblock %} | Treble
    </title>
    <link rel="icon" href="{% static 'treble_logo_icon.png' %}" type="image/png"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"/>
    <link rel="stylesheet" href="{% static 'treble.css' %}"/>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <!-- JQuery needs to be loaded for use on some pages -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark justify-content-between">
            <a class="navbar-brand" href="{% url 'index' %}"><img id="logo" src="{% static 'treble_logo.svg' %}" alt="Treble"></a>
            <div id="navbarCollapse" class="navbar-collapse collapse justify-content-between">
                <ul class="navbar-nav mr-auto">
                    <li><a href="{% url 'most_recommended' %}" class="nav-link">Most recommended</a></li>
                    <li><a href="{% url 'about' %}" class="nav-link">About us</a></li>
                    <li><a href="{% url 'faq' %}" class="nav-link">FAQ</a></li>

                </ul>
                <form class="form-inline mt-2 mt-md-0 nav-link">
                    <input id="search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                </form>
                {% if user.is_authenticated %}
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-add-modal-lg">Add song</button>
                {% endif %}
                <div class="dropdown nav-link">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if user.is_authenticated %}
                            {{ user.username }}
                        {% else %}
                            Log in/Register
                        {% endif %}
                    </button>
                  <div class="dropdown-menu-right dropdown-menu" aria-labelledby="login-dropdown">
                      <!-- These will be different when logged in -->
                      {% if user.is_authenticated %}
                      <a class="dropdown-item" href="{% url 'user_account'%}">My profile</a>
                      <a class="dropdown-item" href="{% url 'auth_logout' %}?next=/treble/">Log out</a>
				      <a class="dropdown-item" href="{% url 'auth_password_change' %}">Change password</a>
				      <a class="dropdown-item" href="{% url 'auth_password_reset' %}">Reset password</a>
                      {% else %}
                      <a class="dropdown-item" href="{% url 'registration_register' %}">Register</a>
                      <a class="dropdown-item" href="{% url 'auth_login' %}?next={{request.path}}">Log in</a>
                      {% endif %}
                  </div>
                </div>
            </div>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
    </header>
    <div class="container">
    {% block body_block %}

    {% endblock %}
    </div>
    <div class="site-footer container-full">
        <div id="footer-image-left"></div><div id="footer-image-right"></div>
    </div>
    <!-- Add Song Modal Start -->
    {% if user.is_authenticated %}
    <div id="add-song-modal" class="modal fade bd-add-modal-lg" tabindex="-1" role="dialog" aria-labelledby="add-song-modal-label" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="add-song-modal-label">Add Song</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="spotify-search">Search with spotify</label>
                            <input type="text" class="form-control" id="spotify-search" placeholder="Search here" autocomplete="off">
                            <ul id="spotify-results">
                                <a href="#" class="d-none" id="result--1">
                                    <li class="row" >
                                        <div class="col-sm-10 col-8">
                                            <p class="result-head"></p>
                                            <p><small class="result-sub"></small></p>
                                        </div>
                                        <div class="col-sm-2 col-4">
                                            <img src="" class="result-img">
                                        </div>
                                    </li>
                                </a>
                            </ul>
                        </div>
                    </form>
                    <div id="manual-add">
                        <form id="add-song-form" action="{% url 'add_song' %}" method="post">
                        {% csrf_token %}
                            {% for field in add_song_form %}
                                <div class="row form-row">
                                    <label for="{{ field.id_for_label }}" class="col-3">{{ field.label }}</label>
                                    {{ field }}
                                </div>
                            {% endfor %}
                        </form>
                    </div>
                </div>
            <div class="modal-footer">
                <button class="btn" id="add-clear">Clear</button>
                <button class="btn btn-primary" type="submit" form="add-song-form">Save</button>
            </div>
            </div>
        </div>
    </div>
    {% endif %}
    <!-- Add Song Modal End -->
    <!-- Load javascript at end of page to speed up load times -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>{%include 'treble/navbar_search.js' %}</script>
    {% include "includes/search_js_stub.html" %}
    {% block additional_js %}{% endblock %}
</body>
</html>

templates/treble/faq.html
{% extends 'treble/base.html' %}
{% load staticfiles %}

{% block title_block %}
    FAQ
{% endblock %}

{% block body_block %}
    <h1>Frequently Asked Questions</h1>
    <hr>
    <div class="title">
        <h3 class="title-text">What is Treble? [+]</h3>
        <p class='info'>
            Ever found a song you really love, but never manage to find anything else quite like it? <br/>
            That's where Treble comes in. We provide a platform for music lovers to share their favourite music,
            recommend songs to other users, and review all kinds of songs!
        </p><br/>
    </div>
    <div class="title">
        <h3 class="title-text">How does it work? [+]</h3>
        <p class='info'>
            Simply <a href='{% url 'registration_register' %}'>sign up</a> for your free account, add your favourite
            songs and you're good to go! <br/>
            The next time someone adds a recommendation to one of your favourites, it will show up on your account page!
        </p><br/>
    </div>
    <div class="title">
        <h3 class="title-text">But where do you get the music metadata? Please tell me I don't have to add it all in
            myself [+]</h3>
        <p class='info'>
            Of course not! <br/>
            We use the Spotify API to ensure you get all the information about any song you want to add, such as
            artwork,
            album, artist and genre, so that you don't have to bother. Just search Spotify for the song you're looking
            for,
            hit "Add Song" and we'll add all the information you need to our database!
        </p><br/>
    </div>
    <div class="title">
        <h3 class="title-text">So how do I add a recommendation or review a song? [+]</h3>
        <p class='info'>
            If you want to add a recommendation, use our intuitive auto-completing search bar to navigate to the song
            you're
            looking for, and add your recommendation. You can either add a song that is already in our database, or
            search Spotify
            for your own addition! <br/>
            If you want to let everyone else know how great (or dissapointing..) a song in our database is, just scroll
            to the bottom
            of the page for that song, and add your review, as well as an emoji reaction to summarise it!
        </p><br/>
    </div>
    <div class="title">
        <h3 class="title-text">Will other people be able to view my profile? [+]</h3>
        <p class='info'>
            Viewing another user's profile is exclusive to user's who have a Treble account and are logged in. If
            another user is logged in
            and wants to view your profile, they can use the search bar, and will be able to see your favourite songs
            and your reviews.
        </p><br/>
    </div>
{% endblock %}

{% block additional_js %}
    <script>{% include "treble/faq_javascript.js" %}</script>
{% endblock %}

templates/treble/index.html
{% extends 'treble/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
    <h1>Welcome to Treble!</h1><br/>
    <h2>Recently Reviewed </h2>
    {% if recently_reviewed %}
        <p>Here is a list of the most recently reviewed songs from our users!</p>
        <div>
            <ul class="link-container">
                {% for song in recently_reviewed %}
                    <li class="song-link">
                        <a href="{% url 'song' song.song_id %}">
                            <img src="{{ song.artwork_url }}"/>
                            <div class="song-title">
                                <p>{{ song.track_name }}</p>
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <h2> oopsie, looks like there's nothing in our database!</h2>
    {% endif %}
    <h2>Recently Added</h2>
    <p>Here is a list of the songs most recently added to our database!</p>
    <div>
        <ul class="link-container">
            {% for song in recently_added %}
                <li class="song-link">
                    <a href="{% url 'song' song.song_id %}">
                        <img src="{{ song.artwork_url }}"/>
                        <div class="song-title">
                            <p>{{ song.track_name }}</p>
                        </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

templates/treble/most_recommended.html
{% extends 'treble/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Most Recommended
{% endblock %}

{% block body_block %}
    <p>Here is a list of the recommended tracks from our users!</p>
    {% if songs %}
        <ul>
            {% for song in songs %}
                <li class="song-link">
                    <a href="{% url 'song' song.song_id %}">
                        <img src="{{ song.artwork_url }}"/>
                        <div class="song-title">
                            <p>{{ song.track_name }}</p>
                        </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h2> oopsie, looks like there's nothing in our database! </h2>
    {% endif %}
{% endblock %}

templates/treble/song.html
{% extends 'treble/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ song.track_name }} - {{ song.artist }}
{% endblock %}

{% block body_block %}
    <div class="row pad-top-1">
        <div class="col-md-4 order-md-2">
            <img id="cover-img" src="{{ song.artwork_url }}"/>
        </div>
        <div id="details" class="col-md-8 order-md-1">
            <h1>{{ song.track_name }}</h1><br />
            <h2>Album: {{ song.album }}</h2>
            <h2>Artist: {{ song.artist }}</h2>
            <h3>{{ song.genre }}</h3>
            <iframe src="https://open.spotify.com/embed?uri={{ song.spotify_uri }}"
        frameborder="0" allow="encrypted-media" allowtransparency="true"></iframe>
        </div>
    </div>
    <div id="similar-to">
        <div class="row">
            <h3>Similar to</h3>
            {% if user.is_authenticated %}
                <div class="left-pad">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-rec-modal-lg">
                        + Add
                    </button>
                </div>
            {% endif %}
        </div>
        <ul class="link-container">
            {% for song in recommended %}
                <li class="song-link">
                    <a href="{% url 'song' song.song_id %}">
                        <img src="{{ song.artwork_url }}"/>
                        <div class="song-title">
                            <p>{{ song.track_name }}</p>
                        </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <!-- TODO: look at structure here, it's quite messy -->
    <div id="reviews">
        <h3>Reviews</h3>
        {% if edit %}
            <div id="edit-comment-row">
        {% else %}
            <div id="comment-row">
        {% endif %}
                {% if user.is_authenticated and form %}
                {% if comment_errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ comment_errors }}
                    </div>
                {% endif %}
                {% if edit %}
                    <form action="{% url 'edit_comment' song.song_id prev_comment_id %}" method="post" id="comment-form">
                {% else %}
                    <form action="{% url 'song_comment' song.song_id %}" method="post" id="comment-form">
                {% endif %}
                    {% csrf_token %}
                    {% for field in form %}
                        {% if not field.is_hidden %}
                        <div class="row form-group">
                            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    {% if edit %}
                        <input type="submit" name="submit" value="Update Review"/>
                    {% else %}
                        <input type="submit" name="submit" value="Submit Review"/>
                    {% endif %}
                </form>
            {% elif not user.is_authenticated %}
                <p><a href="{% url 'auth_login' %}?next={{request.path}}">Log in</a> to add a review</p>
            {% endif %}
        </div>
        <div class="row">
        {% if comments.count > 0 %}
            {% for review in comments %}
                <div class="col-md-6">
                    {% if review.username.id == user.id %}
                        <b>Review by you | </b><a id="edit-comment" href="javascript:void(0)">edit</a><br>
                    {% else %}
                        <b>Review by {{ review.username }}</b><br>
                    {% endif %}
                    <b>Reaction:</b>{{ review.get_reaction_display }}<br>
                    <p class="comment-message">{{ review.message }}</p><br>
                    <p class="comment-date">{{ review.datetime|date:"H.i | j M Y" }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>There are no reviews for this track. Why not add one?</p>
        {% endif %}
        </div>
    </div>
    {% if user.is_authenticated %}
    <div id="add-rec-modal" class="modal fade bd-rec-modal-lg" tabindex="-1" role="dialog" aria-labelledby="add-rec-modal-label" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="add-song-modal-label">Add Recommendation</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                <form id="add-rec-form" action="{% url 'song_recommendation' song_id=song.song_id%}" method="post">
                {% csrf_token %}
                    {% for field in recommend_form %}
                    {{ field }}
                    {% endfor %}
                </form>
                <button type="button" id="add_song" class="btn btn-primary" data-toggle="modal" >Add song</button>
                </div>
            <div class="modal-footer">
                <button class="btn btn-primary" type="submit" form="add-rec-form">Add</button>
            </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}
{% block additional_js %}
    {% include "includes/search_js_stub.html" %}
    <script>{% include "treble/song_comment.js" %}</script>
    <script src="{% static 'dynamic_add_song.js' %}"></script>
{% endblock %}

templates/treble/user_account.html
{% extends 'treble/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Log In
{% endblock %}

{% block body_block %}
    <div>
        <div class="row justify-content-md-left">
            <img class="col-md-auto" id="picture" src="{{ MEDIA_URL }}/{{ user_profile.picture }}"/>
            <h1 class="col col-lg-2">{{ user }}</h1>
        </div>
        <div id="recommended" class="row-1">
            <h1>Recommended for you</h1>
            {% if rec_dict %}
            <div>
                <ul class="link-container">
                    {% for song, reasons in rec_dict.items %}
                        {% if song not in user_profile.favourites.all %}
                            <li class="song-link">
                                <a href="{% url 'song' song.song_id %}">
                                    <img src="{{ song.artwork_url }}"/>
                                    <div class="song-title">
                                        <p>{{ song.track_name }}</p>
                                    </div>
                                </a>
                                <div>
                                    Since you like:
                                    {% for reason in reasons %}
                                        <br/> {{ reason.track_name }}
                                    {% endfor %}
                                </div>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
            {% else %}
            <h3>No recommendations for now </h3>
            {% endif %}
        </div>
        <div id="favourites" class="row-3">
            <div class="row">
                <h1>My Favourites</h1>
                <button type="button" class="btn btn-primary left-margin" data-toggle="modal"
                        data-target=".bd-rec-modal-lg">
                    + Add
                </button>
            </div>
            {% if user_profile.favourites.count > 0 %}
            <div>
                <ul class="link-container">
                    {% for song in user_profile.favourites.all %}
                        <li class="song-link">
                            <a href="{% url 'song' song.song_id %}">
                                <img src="{{ song.artwork_url }}"/>
                                <div class="song-title">
                                    <p>{{ song.track_name }}</p>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            {% else %}
            <h3>Looks like you don't have nay favourites yet. Add some by clicking the "+ Add" button above!</h3>
            {% endif %}
        </div>
        <div id="reviews" class="row-4">
            <h1>My Reviews</h1>
            {% if user_profile.comments.count > 0 %}
            <div>
                <ul class="row review-list">
                    {% for review in user_profile.comments.all %}
                        <div class="col-md-6">
                            <div class='comment-artwork'>
                                <img src="{{ review.song_id.artwork_url }}"/>
                                <b>{{ review.song_id.track_name }}</b>
                                <b>by {{ review.song_id.artist }}</b>
                            </div>
                            <b>Reaction: </b>{{ review.get_reaction_display }}<br>
                            <p class="comment-message">{{ review.message }}</p>
                            <p class="comment-date">{{ review.datetime|date:"H:i | j M Y" }}</p>
                        </div>
                    {% endfor %}
                </ul>
            </div>
            {% else %}
            <h3>Looks like you have not written any reviews yet. Navigate to a song and leave you're opinion on it!</h3>
            {% endif %}
        </div>
        <div id="add-rec-modal" class="modal fade bd-rec-modal-lg" tabindex="-1" role="dialog"
             aria-labelledby="add-rec-modal-label" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 id="add-song-modal-label">Add Favourite</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="add-fav-form" action="{% url 'add_favourite' %}" method="post">
                            {% csrf_token %}
                            {% for field in favourite_form %}
                                {{ field }}
                            {% endfor %}
                        </form>
                        <button type="button" id="add_song" class="btn btn-primary" data-toggle="modal">Add song
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-primary" type="submit" form="add-fav-form">Add</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block additional_js %}
    {% include "includes/search_js_stub.html" %}
    {% include "includes/favourites_js.html" %}
    <script src="{% static 'dynamic_add_song.js' %}"></script>
{% endblock %}

templates/treble/user_profile.html
{% extends 'treble/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ profile }}
{% endblock %}

{% block body_block %}
    <div>
        <div class="row justify-content-md-left">
            <img class="col-md-auto" id="picture" src="{{ MEDIA_URL }}/{{ profile.picture }}"/>
            <h1 class="col col-lg-2">{{ profile }}</h1>

        </div>
        <div id="favourites" class="row-3">
            <h1>{{ profile }}'s Favourites</h1>
            {% if profile.favourites %}
            <div>
                <ul class="link-container">
                    {% for song in profile.favourites.all %}
                        <li class="song-link">
                            <a href="{% url 'song' song.song_id %}">
                                <img src="{{ song.artwork_url }}"/>
                                <div class="song-title">
                                    <p>{{ song.track_name }}</p>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            {% else %}
            <h3>Unfortunately this user doesn't have any favourites</h3>
            {% endif %}
        </div>
        <div id="reviews" class="row-4">
            <h1>{{ profile }}'s Reviews</h1>
            <div>
                <ul class="row review-list">
                    {% if profile.comments.count > 0 %}
                        {% for review in profile.comments.all %}
                            <div class="col-md-6">
                                <div class='comment-artwork'>
                                    <img src="{{ review.song_id.artwork_url }}"/>
                                    <b>{{ review.song_id.track_name }}</b>
                                    <b>by {{ review.song_id.artist }}</b><br/><br/>
                                </div>
                                <b>Reaction: </b>{{ review.get_reaction_display }}<br>
                                <p class="comment-message">{{ review.message }}</p>
                                <p class="comment-date">{{ review.datetime|date:"H:i | j M Y" }}</p>
                            </div>
                        {% endfor %}
                    {% else %}
                    <h3>Unfortunately this user has not written any reviews</h3>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}